#!/Users/doopyduper/Documents/DevOps/Course-Exploring_Deep_Learning/NeuralNetworks/project-bikesharing/venv/bin/python3
# -*- coding: utf-8 -*-
import re
import sys

from udacity_pa.projectassistant import main_func

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main_func())
